name: Build APK

# Jalan otomatis setiap ada push ke branch main
# Bisa juga dijalankan manual lewat tab Actions di GitHub
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies sistem
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake autoconf-archive libtool libltdl-dev pkg-config zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev build-essential gettext m4

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade buildozer cython==0.29.36

      - name: Build APK dengan Buildozer
        env:
          PIP_CONSTRAINT: ${{ github.workspace }}/constraints-pip.txt
          PIP_NO_CACHE_DIR: "1"
          PYTHONDONTWRITEBYTECODE: "1"
        run: |
          yes | buildozer android debug

      - name: Upload hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk
